meta_product_name: "GigMe"
meta_title: "Want to show your music somewhere? Life is short, Gig more!"
meta_description: "Web application design to connect artist with host in a really simple way through the exchange of profiles."
meta_image: "picture_for_test.jpg"
